### PR TITLE
references version update

### PR DESCRIPTION
**Pull request by Malstraem**
Update OpenTK and JetBrains.Annotations to last versions for #61 issue
I also ran into a problem while testing the latest OpenTK version

### CODE REVIEW

**Comment by mathewodwyer** [comment]
I'm really hoping for this, too.

@NogginBops is there any chance we can get these changes merged soon? :)

**Comment by NogginBops** [comment]
@mathewodwyer thanks for the ping! Apparently I've not had notifications for this repository turned on so I've not seen a lot of these PRs and issues. I will push a change to this PR to update to OpenTK 4.7.1, which shouldn't be an issue.

**Comment by NogginBops** [comment]
Ok, turns out I don't have write access to this repo at this moment. Once I've fixed that I'll merge this.

**Comment by mathewodwyer** [comment]
> Ok, turns out I don't have write access to this repo at this moment. Once I've fixed that I'll merge this.

All good, I saw a few PRs here that I've been trying to workaround until they were merged.

**Comment by NogginBops** [comment]
@Malstraem Ping me on discord if you want the contributor role.

**Pull request merged**
